### ISSUE TITLE
Installation problem brtotop on Raspberry Pi3 Raspian Debbie

### ISSUE THREAD

**Issue by edautz** [criticalstack/brotop#2]
I try to install Brotop on an Raspberry PI 3 running raspbian debbie with a running instance of Bro 2.5.

I installed go

I configured GOROOT, PATH according the go installation instructions and GOPATH for a seperate workspace.

and executed (sudo -E for proper path execution) following your instructions.

sudo -E go get github.com/tools/godep
sudo -E go get github.com/jteeuwen/go-bindata/...
 
I come in trouble with:

make

make
make: *** No targets specified and no makefile found.  Stop.

What I expected.

As alternative I tried:

sudo -E go get github.com/criticalstack/brotop
src/github.com/criticalstack/brotop/brotop.go:163: undefined: tail.Cleanup
src/github.com/criticalstack/brotop/server.go:43: undefined: Asset
src/github.com/criticalstack/brotop/server.go:65: undefined: Asset
src/github.com/criticalstack/brotop/server.go:66: undefined: AssetDir

But that doesn't work out.

What do I miss?

**Comment by mephux** [comment]
@edautz updated the build process. Checkout https://github.com/criticalstack/brotop/releases

closing

**Comment by mephux** [comment]
nvm, bug - working on it.

**Comment by mephux** [comment]
ok, fixed for real this time - you can see the build process at http://komanda.io:8080/criticalstack/brotop, and every time we push a tag it will auto deploy a release for all the supported platforms. https://github.com/criticalstack/brotop/releases

**Comment by edautz** [comment]
@mephux It is not clear to me in witch directory I have to start according your installation instructions
 
I got the following go paths:

GOROOT=$HOME/packages/go
GOPATH=$HOME/packages/go/work
PATH=$PATH:$GOPATH/bin
 
I tried several directories 
but get always the following error:


==> Embedding Assets
make: go-bindata: Command not found
Makefile:50: recipe for target 'bindata' failed
make: *** [bindata] Error 127

Can you help me out?

**Comment by mephux** [comment]
@edautz the releases page has a pre-built binary for arm. That wont work for you?

**Comment by mephux** [comment]
@edautz for you error tho.. check the readme https://github.com/criticalstack/brotop#building

**Comment by edautz** [comment]
I downloaded the ARM packages with sudo wget https://github.com/criticalstack/brotop/releases/download/v0.4.0/brotop-linux-arm.tar.gz

after sudo tar –xzf brotop-linux-arm.tar.gz i got a binary called 

brotop

after starting this with ./brotop

it starts up fine:

INFO[0000] Initializing brotop Version: 0.4.0.
INFO[0000] Starting Webserver.
INFO[0000] Opening log files for capture.
INFO[0000] Loading known_hosts.log at /usr/local/bro/logs/current/known_hosts.log
INFO[0000] Loading software.log at /usr/local/bro/logs/current/software.log
INFO[0000] Server listening - http://127.0.0.1:8080
INFO[0000] Loading files.log at /usr/local/bro/logs/current/files.log
INFO[0000] Loading ssl.log at /usr/local/bro/logs/current/ssl.log
INFO[0000] Loading weird.log at /usr/local/bro/logs/current/weird.log
INFO[0000] Loading conn.log at /usr/local/bro/logs/current/conn.log
INFO[0000] Loading ssh.log at /usr/local/bro/logs/current/ssh.log
INFO[0000] Loading x509.log at /usr/local/bro/logs/current/x509.log
INFO[0000] Loading known_services.log at /usr/local/bro/logs/current/known_services.log
INFO[0000] Loading http.log at /usr/local/bro/logs/current/http.log
INFO[0000] Loading loaded_scripts.log at /usr/local/bro/logs/current/loaded_scripts.log
INFO[0000] Loading packet_filter.log at /usr/local/bro/logs/current/packet_filter.log
INFO[0000] Loading smb_mapping.log at /usr/local/bro/logs/current/smb_mapping.log
INFO[0000] Loading capture_loss.log at /usr/local/bro/logs/current/capture_loss.log
INFO[0000] Loading stats.log at /usr/local/bro/logs/current/stats.log
INFO[0000] Loading communication.log at /usr/local/bro/logs/current/communication.log
INFO[0000] Loading dns.log at /usr/local/bro/logs/current/dns.log
INFO[0000] Loading reporter.log at /usr/local/bro/logs/current/reporter.log

But after connecting to brotop on port 8080 i got no connection but the following errors:

2016/11/30 20:07:42 http: panic serving 192.168.2.2:62034: runtime error: invalid memory address or nil pointer dereference
goroutine 62 [running]:
net/http.(*conn).serve.func1(0x10d80a80)
        /usr/local/go/src/net/http/server.go:1491 +0x9c
panic(0x35faf8, 0x10c0a010)
        /usr/local/go/src/runtime/panic.go:458 +0x454
github.com/criticalstack/brotop/vendor/github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0x10d28060, 0x10dc6e20, 0xe, 0x0, 0x0, 0x0, 0x0)
        /drone/src/github.com/criticalstack/brotop/vendor/github.com/elazarl/go-bindata-assetfs/assetfs.go:149 +0x1c0
net/http.serveFile(0x4fbe90, 0x10def5f0, 0x10c15980, 0x4f9b70, 0x10d28060, 0x10dc6bf4, 0x1, 0x1)
        /usr/local/go/src/net/http/fs.go:408 +0x5f4
net/http.(*fileHandler).ServeHTTP(0x10d2a008, 0x4fbe90, 0x10def5f0, 0x10c15980)
        /usr/local/go/src/net/http/fs.go:526 +0x18c
net/http.(*ServeMux).ServeHTTP(0x8da450, 0x4fbe90, 0x10def5f0, 0x10c15980)
        /usr/local/go/src/net/http/server.go:2022 +0x164
net/http.serverHandler.ServeHTTP(0x10d44050, 0x4fbe90, 0x10def5f0, 0x10c15980)
        /usr/local/go/src/net/http/server.go:2202 +0x150
net/http.(*conn).serve(0x10d80a80, 0x4fc368, 0x10dde820)
        /usr/local/go/src/net/http/server.go:1579 +0xde8
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x470


Tried starting brotop als with sudo ./brotop and sudo -E ./brotop, but problem stays the same.
